export const LOGOUT = 'LOGOUT'
export const SET_AUTH = 'SET_AUTH'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_PROGRESS = 'LOGIN_PROGRESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_PROGRESS = 'REGISTER_PROGRESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
